# Generated by Django 4.1.2 on 2022-10-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemon_description_alter_pokemonentity_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(default='Описание на Английском', max_length=200, verbose_name='Название на Английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(default='Описание на Японском', max_length=200, verbose_name='Название на Японском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Описание покемона', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
