# Generated by Django 4.1.2 on 2022-10-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_pokemon_evolution_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokemon_entities.pokemon'),
        ),
    ]
