# Generated by Django 4.1.2 on 2022-10-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_alter_pokemon_evolution_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolution_from',
            new_name='previous_evolution',
        ),
    ]
