# Generated by Django 4.1.2 on 2022-10-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_alter_pokemonentity_appeared_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(upload_to='pokemon_images', verbose_name='Фото покемона'),
        ),
    ]
