# Generated by Django 3.1.14 on 2022-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_auto_20221019_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Покемон удален?'),
        ),
    ]
